# Makefile for offloads

ccflags-y := -I$(obj) -I$(obj)/..
ccflags-y += -Wall -Werror

obj-$(capwap)+= capwap/
obj-$(dtls)+= dtls/
obj-$(pkt_steer) += pkt_steer/
obj-$(flowcookie)+= flow_cookie/
obj ?= .
